### PR TITLE
Undocumented custom error message feature and updated packages

### PR DESCRIPTION
**Pull request by vgdaut**

### CODE REVIEW

**Review by j-tesla — APPROVED** [review]

**Comment by geiszla** [comment]
Any plans for this PR to be merged?

**Comment by j-tesla** [comment]
> 
> 
> Any plans for this PR to be merged?

@blakehaswell

**Comment by vgdaut** [comment]
> > Any plans for this PR to be merged?
> 
> @blakehaswell

It's better to redo the pull request because I changed package author and forgot to remove the change.

**Comment by viveleroi** [comment]
Please rebase this PR. I have included package updates separately, I prefer PRs address specific issues and not bundle things but appreciate the effort.

**Pull request closed without merging**
